-- MySQL Script generated by MySQL Workbench
-- Tue Dec  3 21:21:14 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema UtrechtseFietsenwinkel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema UtrechtseFietsenwinkel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `UtrechtseFietsenwinkel` DEFAULT CHARACTER SET utf8 ;
USE `UtrechtseFietsenwinkel` ;

-- -----------------------------------------------------
-- Table `UtrechtseFietsenwinkel`.`Klant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UtrechtseFietsenwinkel`.`Klant` ;

CREATE TABLE IF NOT EXISTS `UtrechtseFietsenwinkel`.`Klant` (
  `KlantId` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `voornaam` VARCHAR(100) NOT NULL,
  `achternaam` VARCHAR(100) NOT NULL,
  `postcode` VARCHAR(100) NOT NULL,
  `woonplaats` VARCHAR(100) NOT NULL,
  `telefoonnummer` INT NULL,
  `Straat` VARCHAR(100) NOT NULL,
  `huisnummer` INT NOT NULL,
  PRIMARY KEY (`KlantId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UtrechtseFietsenwinkel`.`Factuur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UtrechtseFietsenwinkel`.`Factuur` ;

CREATE TABLE IF NOT EXISTS `UtrechtseFietsenwinkel`.`Factuur` (
  `factuurcode` INT NOT NULL AUTO_INCREMENT,
  `Factuurdatum` DATETIME NOT NULL,
  `id` VARCHAR(100) NOT NULL,
  `btw` INT NOT NULL,
  `Klant_id` INT NOT NULL,
  PRIMARY KEY (`factuurcode`, `Klant_id`),
  INDEX `fk_Factuur_Klant_idx` (`Klant_id` ASC) ,
  CONSTRAINT `fk_Factuur_Klant`
    FOREIGN KEY (`Klant_id`)
    REFERENCES `UtrechtseFietsenwinkel`.`Klant` (`KlantId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UtrechtseFietsenwinkel`.`TypeFiets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UtrechtseFietsenwinkel`.`TypeFiets` ;

CREATE TABLE IF NOT EXISTS `UtrechtseFietsenwinkel`.`TypeFiets` (
  `TypeFietsId` INT NOT NULL AUTO_INCREMENT,
  `TypeFiets` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`TypeFietsId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UtrechtseFietsenwinkel`.`GebruikersRol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UtrechtseFietsenwinkel`.`GebruikersRol` ;

CREATE TABLE IF NOT EXISTS `UtrechtseFietsenwinkel`.`GebruikersRol` (
  `idGebruikersRol` INT NOT NULL,
  `GebruikersRol` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idGebruikersRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UtrechtseFietsenwinkel`.`Gebruikers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UtrechtseFietsenwinkel`.`Gebruikers` ;

CREATE TABLE IF NOT EXISTS `UtrechtseFietsenwinkel`.`Gebruikers` (
  `gebruikersnaam` VARCHAR(100) NOT NULL,
  `wachtwoord` VARCHAR(100) NOT NULL,
  `gebruikersrol` INT NOT NULL,
  PRIMARY KEY (`gebruikersnaam`),
  INDEX `fk_Gebruikers_GebruikersRol_idx` (`gebruikersrol` ASC) ,
  CONSTRAINT `fk_Gebruikers_GebruikersRol`
    FOREIGN KEY (`gebruikersrol`)
    REFERENCES `UtrechtseFietsenwinkel`.`GebruikersRol` (`idGebruikersRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UtrechtseFietsenwinkel`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UtrechtseFietsenwinkel`.`Product` ;

CREATE TABLE IF NOT EXISTS `UtrechtseFietsenwinkel`.`Product` (
  `productCode` INT NOT NULL,
  `productNaam` VARCHAR(100) NOT NULL,
  `kosten` INT NOT NULL,
  `merk` VARCHAR(50) NOT NULL,
  `serie` VARCHAR(100) NOT NULL,
  `TypeFietsId` INT NOT NULL,
  `versnellingen` VARCHAR(100) NULL,
  `frameType` VARCHAR(100) NOT NULL,
  `Garantie` VARCHAR(100) NULL,
  `accuPositie` VARCHAR(100) NULL,
  `oplaatTijd` VARCHAR(100) NULL,
  `capaciteitAccu` VARCHAR(100) NULL,
  `TypeFiets_TypeFietsId` INT NOT NULL,
  `Gebruikers_Gebruikersnaam1` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`productCode`),
  INDEX `fk_Product_TypeFiets1_idx` (`TypeFiets_TypeFietsId` ASC) ,
  INDEX `fk_Product_Gebruikers1_idx` (`Gebruikers_Gebruikersnaam1` ASC) ,
  CONSTRAINT `fk_Product_TypeFiets1`
    FOREIGN KEY (`TypeFiets_TypeFietsId`)
    REFERENCES `UtrechtseFietsenwinkel`.`TypeFiets` (`TypeFietsId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_Gebruikers1`
    FOREIGN KEY (`Gebruikers_Gebruikersnaam1`)
    REFERENCES `UtrechtseFietsenwinkel`.`Gebruikers` (`gebruikersnaam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UtrechtseFietsenwinkel`.`factuurRegel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UtrechtseFietsenwinkel`.`factuurRegel` ;

CREATE TABLE IF NOT EXISTS `UtrechtseFietsenwinkel`.`factuurRegel` (
  `factuurcode` INT NOT NULL AUTO_INCREMENT,
  `productcode` INT NOT NULL,
  `aantal` INT NOT NULL,
  PRIMARY KEY (`factuurcode`, `productcode`),
  INDEX `fk_FactuurRegel_Product_idx` (`productcode` ASC) ,
  CONSTRAINT `fk_FactuurRegel_Factuur`
    FOREIGN KEY (`factuurcode`)
    REFERENCES `UtrechtseFietsenwinkel`.`Factuur` (`factuurcode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FactuurRegel_Product`
    FOREIGN KEY (`productcode`)
    REFERENCES `UtrechtseFietsenwinkel`.`Product` (`productCode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UtrechtseFietsenwinkel`.`reparatie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UtrechtseFietsenwinkel`.`reparatie` ;

CREATE TABLE IF NOT EXISTS `UtrechtseFietsenwinkel`.`reparatie` (
  `reparatieId` INT NOT NULL AUTO_INCREMENT,
  `reparatieSoort` INT NOT NULL,
  `reparatieDatumTijd` DATETIME NOT NULL,
  PRIMARY KEY (`reparatieId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UtrechtseFietsenwinkel`.`ReparatieRegel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UtrechtseFietsenwinkel`.`ReparatieRegel` ;

CREATE TABLE IF NOT EXISTS `UtrechtseFietsenwinkel`.`ReparatieRegel` (
  `KlantId` INT NOT NULL,
  `reparatieId` INT NOT NULL,
  PRIMARY KEY (`KlantId`, `reparatieId`),
  INDEX `fk_ReparatieRegel_reparatie1_idx` (`reparatieId` ASC) ,
  CONSTRAINT `fk_ReparatieRegel_Klant1`
    FOREIGN KEY (`KlantId`)
    REFERENCES `UtrechtseFietsenwinkel`.`Klant` (`KlantId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ReparatieRegel_reparatie1`
    FOREIGN KEY (`reparatieId`)
    REFERENCES `UtrechtseFietsenwinkel`.`reparatie` (`reparatieId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UtrechtseFietsenwinkel`.`afbeelding`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UtrechtseFietsenwinkel`.`afbeelding` ;

CREATE TABLE IF NOT EXISTS `UtrechtseFietsenwinkel`.`afbeelding` (
  `idafbeelding` INT NOT NULL AUTO_INCREMENT,
  `afbeeldingUrl` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idafbeelding`),
  CONSTRAINT `fk_afbeelding_Product`
    FOREIGN KEY (`idafbeelding`)
    REFERENCES `UtrechtseFietsenwinkel`.`Product` (`productCode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
